### ISSUE TITLE
 How to get TABLE page_assessments and TABLE page_assessments_projects?

### ISSUE THREAD

**Issue by XikunHuang** [geohci/wikipedia-language-agnostic-topic-classification#1]
Hello! I want to identify all its WikiProject tags for each English article. I read the original [paper](https://arxiv.org/pdf/2103.00068.pdf) and [Extension:PageAssessments](https://www.mediawiki.org/wiki/Extension:PageAssessments), and it uses two tables **page_assessments**  and **page_assessments_projects** which created by PageAssessments in mediawiki.  I am new to mediawiki, and after google I find that it is not easy for me to create this two tables by myself (If so, I need to import whole wikipedia XML dump into mediawiki, right?).
So, could you share the lastest two tables for **enwiki** or any suggestions to get this two tables?
Thanks a lot!
Xikun

**Comment by geohci** [comment]
Hey Xikun,
Thanks for the interest in this model. Excellent question: these two tables are not included in the monthly dumps unfortunately because they are non-standard tables created by the PageAssessments extension. That said, you can access them in two main ways:
* Quarry (https://meta.wikimedia.org/wiki/Research:Quarry): see this example where I extract just the articles in the Climate Change WikiProject (https://quarry.wmflabs.org/query/52210). You should be able to write to a TSV but I don't know in advance whether the query will be too large to run. This will involve the least amount of setup though so I'd try it first.
* Any of the community compute environments such as Toolforge (https://wikitech.wikimedia.org/wiki/Help:Toolforge) or PAWS (https://wikitech.wikimedia.org/wiki/PAWS). I'd suggest the latter and here are some examples that might have helpful code for accessing the tables (https://wikitech.wikimedia.org/wiki/PAWS/PAWS_examples_and_recipes#Wiki_replicas). I'm more confident that you can get it working in PAWS and then just work with the results there or download for local usage. If it times out though, you might have to break the query into a few parts (e.g., run one part where pageid < 1000000 and a second part where pageid >= 1000000 and then concatenate the results together).

If you find that either of those work for you, let me know and we'll close this issue out and I'll add a note to the README about it.

**Comment by XikunHuang** [comment]
Hello,
I have tried [PAWS](https://wikitech.wikimedia.org/wiki/PAWS) and it works.
The table page_assessments contains too many records, and I break the query into a few parts by page id. I have successfully downloaded this two tables, and here is the notebook [https://public.paws.wmcloud.org/User:Huangxk/export_tables.ipynb](https://public.paws.wmcloud.org/User:Huangxk/export_tables.ipynb).
Thanks for your help.

**Comment by geohci** [comment]
Great, thanks! I added a link to that in the README: https://github.com/geohci/wikipedia-language-agnostic-topic-classification/commit/eed1d0021e15739f8a7580afa0f641517e287812
